<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLocation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('location');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('entity_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('type', 'integer', 2, array('type' => 'integer', 'length' => '2'));
        $this->hasColumn('street', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('city', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('state', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('country', 'string', 2, array('type' => 'string', 'length' => '2'));
        $this->hasColumn('postal_code', 'string', 10, array('type' => 'string', 'length' => '10'));
    }

    public function setUp()
    {
        $this->hasOne('Entity', array('local' => 'entity_id',
                                      'foreign' => 'id',
                                      'onDelete' => 'CASCADE'));
    }
}