<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseComponent extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('component');
    $this->hasColumn('name', 'string', 64, array('type' => 'string', 'length' => '64'));
    $this->hasColumn('project_id', 'string', 4, array('type' => 'string', 'length' => '4'));
    $this->hasColumn('owner_id', 'string', 4, array('type' => 'string', 'length' => '4'));
  }

}