<?php

/**
 * BaseCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $People
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseCompany extends Entity
{
    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Person as People', array('local' => 'id',
                                                 'foreign' => 'parent_id'));
    }
}