<?php

/**
 * BaseMilestone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $project_id
 * @property timestamp $date
 * @property Project $Project
 * @property Doctrine_Collection $Issues
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseMilestone extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('milestone');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('name', 'string', 64, array('type' => 'string', 'length' => '64'));
        $this->hasColumn('project_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('date', 'timestamp', null, array('type' => 'timestamp'));
    }

    public function setUp()
    {
        $this->hasOne('Project', array('local' => 'project_id',
                                       'foreign' => 'id',
                                       'onDelete' => 'CASCADE'));

        $this->hasMany('Issue as Issues', array('local' => 'id',
                                                'foreign' => 'milestone_id'));
    }
}