<?php

/**
 * BasePerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property sfGuardUser $User
 * @property Company $Company
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BasePerson extends Entity
{
    public function setUp()
    {
        parent::setUp();
    $this->hasOne('sfGuardUser as User', array('local' => 'user_id',
                                                   'foreign' => 'id',
                                                   'onDelete' => 'SET NULL'));

        $this->hasOne('Company', array('local' => 'parent_id',
                                       'foreign' => 'id',
                                       'onDelete' => 'SET NULL'));
    }
}