<?php

/**
 * BaseIssueActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $issue_id
 * @property string $verb
 * @property timestamp $created_at
 * @property integer $created_by
 * @property string $body
 * @property string $changes
 * @property Issue $Issue
 * @property sfGuardUser $CreatedBy
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseIssueActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('issue_activity');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('issue_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('verb', 'string', 128, array('type' => 'string', 'length' => '128'));
        $this->hasColumn('created_at', 'timestamp', null, array('type' => 'timestamp'));
        $this->hasColumn('created_by', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('body', 'string', null, array('type' => 'string'));
        $this->hasColumn('changes', 'string', null, array('type' => 'string'));
    }

    public function setUp()
    {
        $this->hasOne('Issue', array('local' => 'issue_id',
                                     'foreign' => 'id',
                                     'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as CreatedBy', array('local' => 'created_by',
                                                        'foreign' => 'id'));
    }
}