<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseIssue extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('issue');
    $this->hasColumn('title', 'string', 128, array('type' => 'string', 'length' => '128'));
    $this->hasColumn('project_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('component_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('assigned_to', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('is_open', 'boolean', null, array('type' => 'boolean'));
    $this->hasColumn('opened_at', 'timestamp', null, array('type' => 'timestamp'));
    $this->hasColumn('opened_by', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('resolved_at', 'timestamp', null, array('type' => 'timestamp'));
    $this->hasColumn('resolved_by', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('closed_at', 'timestamp', null, array('type' => 'timestamp'));
    $this->hasColumn('closed_by', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('status_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('category_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('priority_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('milestone_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('orig_estimate', 'float', null, array('type' => 'float'));
    $this->hasColumn('curr_estimate', 'float', null, array('type' => 'float'));
    $this->hasColumn('elapsed', 'float', null, array('type' => 'float'));
    $this->hasColumn('deadline', 'timestamp', null, array('type' => 'timestamp'));
  }

}