<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePerson extends Entity
{
  public function setUp()
  {
    parent::setUp();
    $this->hasOne('Company', array('local' => 'parent_id',
                                   'foreign' => 'id'));
  }
}