<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseIssueActivity extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('issue_activity');
    $this->hasColumn('issue_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('verb', 'string', 128, array('type' => 'string', 'length' => '128'));
    $this->hasColumn('created_at', 'timestamp', null, array('type' => 'timestamp'));
    $this->hasColumn('created_by', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('body', 'string', null, array('type' => 'string'));
    $this->hasColumn('changes', 'string', null, array('type' => 'string'));
  }

}