<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePriority extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('priority');
    $this->hasColumn('name', 'string', 64, array('type' => 'string', 'length' => '64'));
  }

}