<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComponentTable extends Doctrine_Table
{
  public function getListQuery()
  {
    return $this->createQuery('c')->leftJoin('c.Owner o')->orderBy('c.name');
  }
}
