<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComponentTable extends Doctrine_Table
{
  public function getListQuery()
  {
    return $this->createQuery('c')->leftJoin('c.Owner o')->orderBy('c.name');
  }

  public function getOwner($component_id)
  {
    return Doctrine_Query::create()
      ->select('user.id, user.username')
      ->from('sfGuardUser user')
      ->innerJoin('user.Components c WITH c.id = ?')
      ->fetchOne(array($component_id));
  }

  public function findByProjectQuery($project_id)
  {
    return $this->createQuery('c')
      ->addWhere('c.project_id = ?', array($project_id));
  }

  public function findForAjax($id)
  {
    $components = $this->createQuery('c')
      ->select('c.id, c.name')
      ->addWhere('c.project_id = ?', $id)
      ->addOrderBy('c.name')
      ->execute();

    $list = array();
    foreach ($components as $component)
    {
      $list[$component['id']] = $component['name'];
    }

    return $list;
  }
}
