<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Company extends BaseCompany
{
  public function __toString()
  {
    if (is_null($this->name))
    {
      return ' - ';
    }
    else
    {
      return $this->name;
    }
  }
}
