<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComponentTable extends Doctrine_Table
{
  public function getListQuery()
  {
    return $this->createQuery('c')->leftJoin('c.Owner o')->orderBy('c.name');
  }

  public function getOwner($component_id)
  {
    return Doctrine_Query::create()
      ->select('user.id, user.username')
      ->from('sfGuardUser user')
      ->innerJoin('user.Components c WITH c.id = ?')
      ->fetchOne(array($component_id));
  }
}
