<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Email extends BaseEmail
{
  static $types = array(
    1 => 'Work',
    2 => 'Home',
    3 => 'Other',
  );

  public function getTypeName()
  {
    return self::$types[$this->type];
  }
}
