<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntityTable extends Doctrine_Table
{
  public function getOrCreate($company_name)
  {
    $company = $this->findOneBy('name', $company_name);
    if ( $company !== false )
    {
      return $company;
    }
    else
    {
      return $this->create(array('name' => $company_name));
    }
  }

  public function findForAjax($q, $limit)
  {
    $entities = $this->createQuery('e')
      ->select('e.name')
      ->addWhere('e.name LIKE ?', $q . '%')
      ->addOrderBy('e.name')
      ->limit($limit)
      ->execute();

    $list = array();
    foreach ($entities as $entity)
    {
      $list[(string) $entity] = (string) $entity;
    }

    return $list;
  }

  public function getForShow($parameters)
  {
    return $this->getShowQuery($parameters)->fetchOne();
  }

  public function getShowQuery($parameters)
  {
    return $this->createQuery('e')
      ->leftJoin('e.Phonenumbers p')
      ->leftJoin('e.Emails em')
      ->leftJoin('e.Locations loc')
      ->addWhere('e.id = ?', $parameters['id'])
    ;
  }
}
