<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Entity extends BaseEntity
{
  public function getNotesList()
  {
    return Doctrine::getTable('Note')->getListQuery()
      ->addWhere('n.entity_id = ?', $this->id)
      ->execute();
  }
}
