<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IssueActivity extends BaseIssueActivity
{
  public $blackList = array(
    'is_closed', 'opened_at', 'opened_by', 'resolved_at',
    'is_resolved', 'resolved_by', 'closed_at', 'closed_by',
    'assigned_to', 'status_id'
  );

  public function setIssueAndChanges(Issue $issue, array $old_values)
  {
    $this->issue_id = $issue->id;
    $this->changes = $this->calculateChanges($issue, $old_values);
    $this->verb = $this->calculateVerb($issue);
  }

  protected function calculateVerb(Issue $issue)
  {
    $modified = $issue->getModified();
    if (!$issue->exists())
    {
      return 'Opened (assigned to ' . $issue->AssignedTo . ')';
    }
    else if (in_array('is_closed', array_keys($modified)))
    {
      if ($issue->isClosed())
      {
        return 'Closed';
      }
      else
      {
        return 'Reopened (assigned to ' . $issue->AssignedTo . ')';
      }
    }
    else if (in_array('is_resolved', array_keys($modified)))
    {
      if ($issue->isResolved())
      {
        return (string) $issue->Status;
      }
      else
      {
        return 'Reactivated (assigned to ' . $issue->AssignedTo . ')';
      }
    }
    else if (in_array('assigned_to', array_keys($modified)))
    {
      return 'Assigned to ' . $issue->AssignedTo;
    }
    else
    {
      return 'Edited';
    }
  }

  protected function calculateChanges(Issue $issue, array $old_values)
  {
    $changes = array();
    $modified = $issue->getModified();
    foreach ($modified as $field => $value)
    {
      if (!in_array($field, $this->blackList))
      {
        $field_name = $this->getIssueFieldName($field);
        $old_value = $this->getIssueFieldValue($field, $issue, $old_values, false);
        $new_value = $this->getIssueFieldValue($field, $issue, $old_values, true);
        $changes[] = "$field_name changed from '$old_value' to '$new_value'.";
      }
    }
    return implode("\n", $changes);
  }

  protected function getIssueFieldName($field)
  {
    return Doctrine_Inflector::classify(str_replace('_id', '', $field));
  }

  /**
   * @arg refresh - get old values or new values?
   */
  protected function getIssueFieldValue($field, $issue, $old_values, $refresh = false)
  {
    if ($issue[$field] && strpos($field, '_id') !== false)
    {
      if ($refresh)
      {
        $issue->refreshRelated($this->getIssueFieldName($field));
      }
      return $issue[$this->getIssueFieldName($field)];
    }
    else
    {
      if ($refresh)
      {
        return $issue[$field];
      }
      else
      {
        return $old_values[$field];
      }
    }
  }

  public function preInsert($event)
  {
    $modified = $this->getModified();
    if (!array_key_exists('created_at', $modified))
    {
      $this->created_at = date('Y-m-d H:i:s');
    }
    if (!array_key_exists('created_by', $modified))
    {
      $this->created_by = Listener_Userstampable::getCurrentUserId();
    }
  }
}

