<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Issue extends BaseIssue
{
  public function isOpen()
  {
    return $this->is_open;
  }

  public function isResolved()
  {
    return ($this->status_id > 1);
  }
}

