<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MilestoneTable extends Doctrine_Table
{
  public function getListQuery()
  {
    return $this->createQuery('m')->orderBy('m.date desc');
  }
}
