<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MilestoneTable extends Doctrine_Table
{
  public function getListQuery()
  {
    return $this->createQuery('m')->orderBy('m.date desc');
  }

  public function findByProjectQuery($project_id)
  {
    return $this->createQuery('m')
      ->addWhere('m.project_id = ?', array($project_id));
  }

  public function findForAjax($id)
  {
    $milestones = $this->createQuery('m')
      ->select('m.id, m.name')
      ->addWhere('m.project_id = ?', $id)
      ->addOrderBy('m.name')
      ->execute();

    $list = array();
    foreach ($milestones as $milestone)
    {
      $list[$milestone['id']] = $milestone['name'];
    }

    return $list;
  }
}
