<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MilestoneTable extends Doctrine_Table
{
  public function getListQuery()
  {
    return $this->createQuery('m')->orderBy('m.date desc');
  }

  public function findByProjectQuery($project_id)
  {
    return $this->createQuery('m')
      ->addWhere('m.project_id = ?', array($project_id));
  }
}
