<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NoteTable extends Doctrine_Table
{
  public function getListQuery()
  {
    return $this->createQuery('n')
      ->leftJoin('n.CreatedBy')
      ->orderBy('n.created_at desc')
    ;
  }
}
