<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonTable extends EntityTable
{
  public function findForList()
  {
    return $this->createQuery('p')
      ->leftJoin('p.Company c')
      ->leftJoin('p.Phonenumbers phones')
      ->leftJoin('p.Emails emails')
      ->execute();
  }
}
