<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Person extends BasePerson
{
  public function getShowUrl()
  {
    return sfContext::getInstance()->getRouting()->generate('people_show', $this);
  }
}
