<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Priority extends BasePriority
{
  public function __toString()
  {
    return $this->id . '. ' . $this->name;
  }
}
