<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectTable extends Doctrine_Table
{
  public function getForShow($parameters)
  {
    return $this->getShowQuery($parameters)->fetchOne();
  }

  public function getListQuery()
  {
    return $this->createQuery('p')
      ->leftJoin('p.Client e')
      ->leftJoin('p.Owner o')
      ->addOrderBy('p.name');
  }

  public function getShowQuery($parameters)
  {
    return $this->createQuery('p')
      ->leftJoin('p.Client c')
      ->leftJoin('p.Owner o')
      ->addWhere('p.id = ?', $parameters['id'])
    ;
  }
}
