<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Project extends BaseProject
{
  public function getNotesList()
  {
    return Doctrine::getTable('Note')->getListQuery()
      ->addWhere('n.project_id = ?', $this->id)
      ->execute();
  }

  public function getMilestonesList()
  {
    return Doctrine::getTable('Milestone')->getListQuery()
      ->addWhere('m.project_id = ?', $this->id)
      ->execute();
  }

  public function getComponentsList()
  {
    return Doctrine::getTable('Component')->getListQuery()
      ->addWhere('c.project_id = ?', $this->id)
      ->execute();
  }

  public function __toString()
  {
    return ($this->name) ? $this->name : 'Undefined';
  }
}
