<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectTable extends Doctrine_Table
{
  public function getListQuery()
  {
    return $this->createQuery('p')
      ->leftJoin('p.Entity e')
      ->addOrderBy('p.name');
  }
}
