<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectTable extends Doctrine_Table
{
  public function getForShow($parameters)
  {
    return $this->getShowQuery($parameters)->fetchOne();
  }

  public function getListQuery()
  {
    return $this->createQuery('p')
      ->leftJoin('p.Client e')
      ->leftJoin('p.Owner o')
      ->addOrderBy('p.name');
  }

  public function getShowQuery($parameters)
  {
    return $this->createQuery('p')
      ->leftJoin('p.Client c')
      ->leftJoin('p.Owner o')
      ->addWhere('p.id = ?', $parameters['id'])
    ;
  }

  public function getOwner($project_id)
  {
    return Doctrine_Query::create()
      ->select('user.id, user.username')
      ->from('sfGuardUser user')
      ->innerJoin('user.Projects p WITH p.id = ?')
      ->fetchOne(array($project_id));
  }
}
