<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Status extends BaseStatus
{
  public function __toString()
  {
    return ($this->is_resolved ? 'Resolved' : 'Active') . ' - ' . $this->name;
  }
}
