<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUser extends PluginsfGuardUser
{
  public function __toString()
  {
    if ($this->exists()) {
      return $this->getUsername();
    } else {
      return '';
    }
  }
}
