all:
  max_entities_on_contacts: 10
  max_projects_on_index: 10
  max_issues_on_index: 50

  zend_lib_dir: /usr/share/php5/zf-lib-1.7

  smtp:
    ssl: tls
    port: 587
    auth: login
    server: smtp.gmail.com
    username: username@gmail.com
    password: password
