issues:
  class: sfDoctrineRouteCollection
  options:
    model:      Issue
    with_show:  true
    model_methods: { object: getForShow }
    collection_actions: { filter: post, batch: post, batchUpdate: post, search: get }

people:
  class: sfDoctrineRouteCollection
  options:
    model:      Person
    with_show:  true

companies:
  class: sfDoctrineRouteCollection
  options:
    model:      Company
    with_show:  true

projects:
  class: sfDoctrineRouteCollection
  options:
    model:      Project
    with_show:  true
    model_methods: { object: getForShow }
    collection_actions: { filter: get }

users:
  class: sfDoctrineRouteCollection
  options:
    model:      sfGuardUser
    object_actions: { password: get, password_update: put }

notes_create:
  url:     /notes
  class:   sfDoctrineRoute
  options: { model: Note, type: object }
  param:   { module: notes, action: create }
  requirements: { sf_method: POST }

contacts_show:
  url:      /contacts/:id
  class:    sfDoctrineRoute
  options:  { model: Entity, type: object, method: getForShow }
  param:    { module: contacts, action: show }
  requirements: { sf_method: GET }

contacts_ajax:
  url:   /contacts.json
  param: { module: contacts, action: ajaxList }

contacts:
  url:   /contacts
  param: { module: contacts, action: index }

homepage:
  url:   /
  param: { module: contacts, action: index }

# secondary
milestones:
  class: sfDoctrineRouteCollection
  options:
    model: Milestone
    collection_actions: { ajaxList: get }

components:
  class: sfDoctrineRouteCollection
  options:
    model: Component
    collection_actions: { ajaxList: get }

# default rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
