default:
  http_metas:
    content-type: text/html

  metas:
    title:        Axai Manager
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [960/reset.css, 960/text.css, 960/960.css, main]

  javascripts:    [jquery.js]

  has_layout:     true
  layout:         layout
