prod:
  doctrine:
    param:
      dsn:        mysql:dbname=cms_prod;host=localhost

test:
  doctrine:
    param:
      dsn:        mysql:dbname=cms_test;host=localhost

all:
  doctrine:
    class:        sfDoctrineDatabase
    param:
      dsn:        mysql:dbname=cms;host=localhost
      username:   root
      password:   
      encoding:   utf8
      persistent: true
      pooling:    true

