test:
  doctrine:
    param:
#      classname:  DebugPDO
      dsn:        mysql:dbname=cms_test;host=localhost

all:
  doctrine:
    class:        sfDoctrineDatabase
    param:
#      classname:  PropelPDO
      dsn:        mysql:dbname=cms;host=localhost
      username:   root
      password:   
      encoding:   utf8
      persistent: true
      pooling:    true

