Entity:
  actAs: [Timestampable]
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    name:
      type:         string(255)
      notnull:     true
    code:
      type:         string(50)
      unique:       true
    type:           integer(2)
    parent_id:      integer(4)

Person:
  inheritance:
    extends:        Entity
    keyValue:       1
  columns:
    title:          string(255)
  relations:
    Company:
      foreignAlias: People
      local:        parent_id

Company:
  inheritance:
    extends:        Entity
    keyValue:       2

Phonenumber:
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    entity_id:      integer(4)
    number:         string(50)
    type:           integer(2)
  relations:
    Entity:
      foreignAlias: Phonenumbers
      onDelete:     CASCADE

Email:
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    entity_id:      integer(4)
    email:
      type:         string(50)
      email:        true
    type:           integer(2)
  relations:
    Entity:
      foreignAlias: Emails
      onDelete:     CASCADE

Location:
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    entity_id:      integer(4)
    type:           integer(2)
    street:         string(255)
    city:           string(50)
    state:          string(50)
    country:        string(2)
    postal_code:    string(10)
  relations:
    Entity:
      foreignAlias: Locations
      onDelete:     CASCADE
