Entity:
  actAs: [Timestampable]
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    name:
      type:         string(255)
      notnull:     true
    code:
      type:         string(50)
      unique:       true
    type:           integer(2)
    user_id:        integer
    owner_id:       integer
    parent_id:      integer(4)
    description:    string
  relations:
    Owner:
      local:        owner_id
      class:        sfGuardUser
      foreignAlias: Clients
      onDelete:     SET NULL

Person:
  inheritance:
    extends:        Entity
    keyValue:       1
  columns:
    title:          string(255)
  relations:
    User:
      local:        user_id
      class:        sfGuardUser
      onDelete:     SET NULL
      foreignType:  one
    Company:
      foreignAlias: People
      local:        parent_id
      onDelete:     SET NULL
# TODO: make sure you ask before deleting a parent entity for its children

Company:
  inheritance:
    extends:        Entity
    keyValue:       2

Phonenumber:
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    entity_id:      integer(4)
    number:         string(50)
    type:           integer(2)
  relations:
    Entity:
      foreignAlias: Phonenumbers
      onDelete:     CASCADE

Email:
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    entity_id:      integer(4)
    email:
      type:         string(50)
      email:        true
    type:           integer(2)
  relations:
    Entity:
      foreignAlias: Emails
      onDelete:     CASCADE

Location:
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    entity_id:      integer(4)
    type:           integer(2)
    street:         string(255)
    city:           string(50)
    state:          string(50)
    country:        string(2)
    postal_code:    string(10)
  relations:
    Entity:
      foreignAlias: Locations
      onDelete:     CASCADE
