Project:
  actAs: [Timestampable]
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    name:
      type:         string(50)
      notnull:      true
    description:    string
    client_id:      integer(4)
    owner_id:       integer
  relations:
    Owner:
      local:        owner_id
      class:        sfGuardUser
      foreignAlias: Projects
      onDelete:     SET NULL

Note:
  actAs: [Timestampable, Userstampable]
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    entity_id:      integer(4)
    project_id:     integer(4)
    body:           string
  relations:
    Project:
      foreignAlias: Notes
      onDelete:     CASCADE

