MailQueue:
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    created_at:     timestamp
    subject:        string(255)
    recipients:     string
    body:           string
    max_attemps:    { type: integer(1), default: 3 }
    attemps:        { type: integer(1), default: 0 }
