<?php

/**
 * BaseMailQueue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $created_at
 * @property string $subject
 * @property string $recipients
 * @property string $body
 * @property integer $max_attemps
 * @property integer $attemps
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseMailQueue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mail_queue');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('created_at', 'timestamp', null, array('type' => 'timestamp'));
        $this->hasColumn('subject', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('recipients', 'string', null, array('type' => 'string'));
        $this->hasColumn('body', 'string', null, array('type' => 'string'));
        $this->hasColumn('max_attemps', 'integer', 1, array('type' => 'integer', 'default' => '3', 'length' => '1'));
        $this->hasColumn('attemps', 'integer', 1, array('type' => 'integer', 'default' => 0, 'length' => '1'));
    }

}